import type { AssetClass } from "@/lib/supported-assets";

export type SearchItem = {
  assetClass: AssetClass;
  name: string;
  symbol: string;
  keywords: string[];
};

export const SYMBOL_SEARCH_DATA: SearchItem[] = [
  {
    assetClass: "kr_stock",
    name: "삼성전자",
    symbol: "005930",
    keywords: ["삼성전자", "삼성", "samsung electronics", "005930"],
  },
  {
    assetClass: "kr_stock",
    name: "SK하이닉스",
    symbol: "000660",
    keywords: ["sk하이닉스", "하이닉스", "sk hynix", "000660"],
  },
  {
    assetClass: "kr_stock",
    name: "NAVER",
    symbol: "035420",
    keywords: ["naver", "네이버", "035420"],
  },
  {
    assetClass: "kr_stock",
    name: "카카오",
    symbol: "035720",
    keywords: ["카카오", "kakao", "035720"],
  },
  {
    assetClass: "kr_stock",
    name: "LG에너지솔루션",
    symbol: "373220",
    keywords: ["lg에너지솔루션", "lg energy solution", "373220", "엘지에너지솔루션"],
  },
  {
    assetClass: "kr_stock",
    name: "현대차",
    symbol: "005380",
    keywords: ["현대차", "hyundai motor", "005380", "현대자동차"],
  },
  {
    assetClass: "kr_stock",
    name: "기아",
    symbol: "000270",
    keywords: ["기아", "kia", "000270"],
  },
  {
    assetClass: "kr_stock",
    name: "셀트리온",
    symbol: "068270",
    keywords: ["셀트리온", "celltrion", "068270"],
  },
  {
    assetClass: "kr_stock",
    name: "삼성바이오로직스",
    symbol: "207940",
    keywords: ["삼성바이오로직스", "samsung biologics", "207940"],
  },
  {
    assetClass: "kr_stock",
    name: "POSCO홀딩스",
    symbol: "005490",
    keywords: ["posco", "포스코", "posco홀딩스", "005490"],
  },
  {
    assetClass: "kr_stock",
    name: "한화에어로스페이스",
    symbol: "012450",
    keywords: ["한화에어로스페이스", "hanwha aerospace", "012450", "한화에어로"],
  },
  {
    assetClass: "kr_stock",
    name: "HD현대중공업",
    symbol: "329180",
    keywords: ["hd현대중공업", "현대중공업", "329180", "hd hyundai heavy industries"],
  },
  {
    assetClass: "kr_stock",
    name: "두산에너빌리티",
    symbol: "034020",
    keywords: ["두산에너빌리티", "doosan energetility", "034020", "두산"],
  },
  {
    assetClass: "kr_stock",
    name: "알테오젠",
    symbol: "196170",
    keywords: ["알테오젠", "alteogen", "196170"],
  },
  {
    assetClass: "kr_stock",
    name: "에코프로비엠",
    symbol: "247540",
    keywords: ["에코프로비엠", "ecopro bm", "247540", "에코프로"],
  },
  {
    assetClass: "kr_stock",
    name: "삼성물산",
    symbol: "028260",
    keywords: ["삼성물산", "samsung c&t", "028260"],
  },
  {
    assetClass: "kr_stock",
    name: "KB금융",
    symbol: "105560",
    keywords: ["kb금융", "kb financial", "105560"],
  },
  {
    assetClass: "kr_stock",
    name: "신한지주",
    symbol: "055550",
    keywords: ["신한지주", "shinhan", "055550"],
  },
  {
    assetClass: "us_stock",
    name: "Apple",
    symbol: "AAPL",
    keywords: ["apple", "aapl", "애플"],
  },
  {
    assetClass: "us_stock",
    name: "Microsoft",
    symbol: "MSFT",
    keywords: ["microsoft", "msft", "마이크로소프트"],
  },
  {
    assetClass: "us_stock",
    name: "NVIDIA",
    symbol: "NVDA",
    keywords: ["nvidia", "nvda", "엔비디아"],
  },
  {
    assetClass: "us_stock",
    name: "Tesla",
    symbol: "TSLA",
    keywords: ["tesla", "tsla", "테슬라"],
  },
  {
    assetClass: "us_stock",
    name: "Amazon",
    symbol: "AMZN",
    keywords: ["amazon", "amzn", "아마존"],
  },
  {
    assetClass: "us_stock",
    name: "Alphabet Class A",
    symbol: "GOOGL",
    keywords: ["alphabet", "google", "googl", "구글", "알파벳"],
  },
  {
    assetClass: "us_stock",
    name: "Meta Platforms",
    symbol: "META",
    keywords: ["meta", "facebook", "meta platforms", "메타", "페이스북"],
  },
  {
    assetClass: "us_stock",
    name: "Broadcom",
    symbol: "AVGO",
    keywords: ["broadcom", "avgo", "브로드컴"],
  },
  {
    assetClass: "us_stock",
    name: "Palantir Technologies",
    symbol: "PLTR",
    keywords: ["palantir", "pltr", "팔란티어"],
  },
  {
    assetClass: "us_stock",
    name: "Berkshire Hathaway Class B",
    symbol: "BRK.B",
    keywords: ["berkshire", "brk.b", "brk-b", "버크셔", "버크셔 해서웨이"],
  },
  {
    assetClass: "us_stock",
    name: "Advanced Micro Devices",
    symbol: "AMD",
    keywords: ["amd", "advanced micro devices", "에이엠디"],
  },
  {
    assetClass: "us_stock",
    name: "Taiwan Semiconductor Manufacturing",
    symbol: "TSM",
    keywords: ["tsm", "tsmc", "taiwan semiconductor", "대만반도체"],
  },
  {
    assetClass: "us_stock",
    name: "Netflix",
    symbol: "NFLX",
    keywords: ["netflix", "nflx", "넷플릭스"],
  },
  {
    assetClass: "us_stock",
    name: "Coinbase Global",
    symbol: "COIN",
    keywords: ["coinbase", "coin", "코인베이스"],
  },
  {
    assetClass: "us_stock",
    name: "Robinhood Markets",
    symbol: "HOOD",
    keywords: ["robinhood", "hood", "로빈후드"],
  },
  {
    assetClass: "us_stock",
    name: "Super Micro Computer",
    symbol: "SMCI",
    keywords: ["super micro", "smci", "슈퍼마이크로", "super micro computer"],
  },
  {
    assetClass: "us_stock",
    name: "Oracle",
    symbol: "ORCL",
    keywords: ["oracle", "orcl", "오라클"],
  },
  {
    assetClass: "us_stock",
    name: "ServiceNow",
    symbol: "NOW",
    keywords: ["servicenow", "now", "서비스나우"],
  },
  {
    assetClass: "us_stock",
    name: "Invesco QQQ Trust",
    symbol: "QQQ",
    keywords: ["qqq", "invesco qqq", "나스닥 etf"],
  },
  {
    assetClass: "us_stock",
    name: "SPDR S&P 500 ETF",
    symbol: "SPY",
    keywords: ["spy", "spdr", "s&p 500 etf", "sp500 etf"],
  },
  {
    assetClass: "crypto",
    name: "Bitcoin",
    symbol: "BTC",
    keywords: ["bitcoin", "btc", "비트코인"],
  },
  {
    assetClass: "crypto",
    name: "Ethereum",
    symbol: "ETH",
    keywords: ["ethereum", "eth", "이더리움"],
  },
  {
    assetClass: "crypto",
    name: "Solana",
    symbol: "SOL",
    keywords: ["solana", "sol", "솔라나"],
  },
  {
    assetClass: "crypto",
    name: "Dogecoin",
    symbol: "DOGE",
    keywords: ["dogecoin", "doge", "도지코인"],
  },
  {
    assetClass: "crypto",
    name: "Ripple",
    symbol: "XRP",
    keywords: ["ripple", "xrp", "리플"],
  },
  {
    assetClass: "crypto",
    name: "Cardano",
    symbol: "ADA",
    keywords: ["cardano", "ada", "카르다노"],
  },
  {
    assetClass: "crypto",
    name: "Binance Coin",
    symbol: "BNB",
    keywords: ["binance coin", "bnb", "바이낸스코인"],
  },
  {
    assetClass: "crypto",
    name: "TRON",
    symbol: "TRX",
    keywords: ["tron", "trx", "트론"],
  },
  {
    assetClass: "crypto",
    name: "Avalanche",
    symbol: "AVAX",
    keywords: ["avalanche", "avax", "아발란체"],
  },
  {
    assetClass: "crypto",
    name: "Chainlink",
    symbol: "LINK",
    keywords: ["chainlink", "link", "체인링크"],
  },
  {
    assetClass: "crypto",
    name: "Sui",
    symbol: "SUI",
    keywords: ["sui", "수이"],
  },
  {
    assetClass: "crypto",
    name: "Toncoin",
    symbol: "TON",
    keywords: ["toncoin", "ton", "톤코인"],
  },
  {
    assetClass: "crypto",
    name: "Polkadot",
    symbol: "DOT",
    keywords: ["polkadot", "dot", "폴카닷"],
  },
  {
    assetClass: "crypto",
    name: "Shiba Inu",
    symbol: "SHIB",
    keywords: ["shiba inu", "shib", "시바이누"],
  },
  {
    assetClass: "crypto",
    name: "Litecoin",
    symbol: "LTC",
    keywords: ["litecoin", "ltc", "라이트코인"],
  },
  {
    assetClass: "crypto",
    name: "Bitcoin Cash",
    symbol: "BCH",
    keywords: ["bitcoin cash", "bch", "비트코인캐시"],
  },
  {
    assetClass: "crypto",
    name: "Pepe",
    symbol: "PEPE",
    keywords: ["pepe", "페페"],
  },
  {
    assetClass: "crypto",
    name: "Aptos",
    symbol: "APT",
    keywords: ["aptos", "apt", "앱토스"],
  },
  {
    assetClass: "crypto",
    name: "NEAR Protocol",
    symbol: "NEAR",
    keywords: ["near", "near protocol", "니어"],
  },
];
